getv: Status code broke in HEAD^, fixing

diff --git a/getv b/getv
--- a/getv
+++ b/getv
@@ -182,10 +182,11 @@ sched_dump ()
 	        ${Url}                                     \
 	      ||
 	    {
+	        Capture_status=\$?
 	        # Wait for yt-dlp / ffmpeg to finish:
 	        sleep 4
 	        echo
-	        echo "Capture failed (\$?), cleaning up:"
+	        echo "Capture failed (\$Capture_status), cleaning up:"
 	        rm -rv "${Ext_name}"*.part
 	        exit
 	    }
